-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SEQUENCE "public"."Roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."delphi_chi_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."qtn_key_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "projects" (
	"id" integer PRIMARY KEY NOT NULL,
	"pid" integer NOT NULL,
	"name" varchar(500),
	"description" text NOT NULL,
	"createdAt" timestamp with time zone,
	"updateAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "commits" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Commit_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"cid" text NOT NULL,
	"author_email" text,
	"author_name" text,
	"authored_date" timestamp with time zone,
	"committed_date" timestamp with time zone,
	"committer_email" text,
	"committer_name" text,
	"created_at" timestamp with time zone,
	"title" text,
	"message" text,
	"project_id" integer,
	"short_id" text,
	"stats_additions" integer,
	"stats_deletions" integer,
	"stats_total" integer,
	"status" text
);

*/